spring:
  redis:
    uri: ${REDIS_URI}

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: 

weather_api_key: ${WEATHER_API_KEY}

